name: Run Prettier
on:
    push:
        branches: [master]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            # Downloads Repos for Usage
            - uses: actions/checkout@v2

            # Runs prettier
            - name: Format with prettier
              uses: actionsx/prettier@v2
              with:
                  args: --config .prettierrc --write . --list-different

            - name: Add & Commit
              uses: EndBug/add-and-commit@v7.3.0
              with:
                  message: Apply prettier changes.
                  default_author: github_actions